### ISSUE TITLE
Missing some files

### ISSUE THREAD

**Issue by Canefis** [LiquidLayerOff/LILA-Blockchain#1]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Canefis** [comment]
Genesis config file

**Comment by LiquidLayerOff** [comment]
https://github.com/LiquidLayerOff/LILA-Ecosystem/blob/master/mainnet/genesic.json
